easy_admin:
    entities:
        # List the entity class name you want to manage
        Post:
            class: App\Entity\Post
            label: 'Customers'
            list:
                title: "Most recent post"
            form:
                fields:
                    - { property: 'title' }
                    - { property: 'content', type: 'FOS\CKEditorBundle\Form\Type\CKEditorType' }
                    - { property: 'created_at' }
                    - { property: 'updated_at' }
        #- App\Entity\Post
        #Post:
        #    - App\Entity\Post
        #        form:
        #            fields:
        #                - { property: 'content', type: 'ckeditor' }
#        - App\Entity\Category
        User:
            class: App\Entity\User
    site_name: 'Maquette'
    design:
        brand_color: '#1ABC9C'
