fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: danone97200@gmail.com
        sender_name: test
    registration:
        confirmation:
            enabled: true    