vich_uploader:
    db_driver: orm
    #storage:    file_system

    mappings:
        post_image:
            uri_prefix: images/post  #dev
            upload_destination: '%kernel.project_dir%/public/images/post'
            #namer: Vich\UploaderBundle\Naming\OrignameNamer
